### PR TITLE
Add a rule to prevent passing methods as props to React components

### PR DESCRIPTION
**Pull request by kevinbarabash**
This should come in handy as we convert more createReactClass components to using ES6 style classes.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
One thing that this rule doesn't handle is nested class components.  I don't think that's something we should bother supporting.  If we spot that construct in our code would should get rid of it.

**Comment by kevinbarabash** [comment]
@jeresig I'll check and report back here.
@somewhatabstract I was thinking to create new rules in this package and then submit PRs to the appropriate plugins, e.g. `eslint-plugin-react` later.  Once the PR for a specific rule gets merged there we can deprecate it here.

**Comment by kevinbarabash** [comment]
I found the following violations in webapp:
```
javascript/class-package/content/topic-row.jsx:528:17: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/class-package/content/topic-row.jsx:529:17: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/components/modal-package/video-modal.jsx:350:25: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/content-library-package/modules/content-list.jsx:262:21: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/logged-in-homepage-package/content-pages/missions-skills.jsx:170:37: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/logged-out-homepage-package/modules/last-chance.jsx:109:29: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/referrals-package/ambassador-dashboard.jsx:107:21: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/sat-mission-package/components/overview-banners/register-for-sat-banner.jsx:123:29: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/video-package/end-of-video-card.jsx:381:17: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
javascript/video-package/video-player/video-player.jsx:615:29: E@khanacademy/react-no-method-jsx-attribute Methods cannot be passed as props, use a class property instead. (Mute with // eslint-disable-line @khanacademy/react-no-method-jsx-attribute)
```

**Comment by jeresig** [comment]
@kevinbarabash Fascinating! Some of these aren't bugs (in that they never use `this`) but at least two of these are a failure: `javascript/logged-in-homepage-package/content-pages/missions-skills.jsx` and `javascript/video-package/end-of-video-card.jsx`

**Comment by kevinbarabash** [comment]
One of these files was using a `get`ter method so I'll have to update the rule to handle that case.

**Comment by kevinbarabash** [comment]
This rule does check that a class extends React.Component (or PureComponent).  I think this is okay because the likelihood of having a class that uses JSX that isn't a component is very low.

**Comment by kevinbarabash** [comment]
> Some of these aren't bugs (in that they never use this)

Even if they don't use `this` at the moment, someone could add `this` to the method and forget to change it to a class property.

**Pull request merged**
